#!/bin/zsh

# System Info
neofetch

# Environment Variables
export PATH="$HOME/.local/bin:$PATH"
export PATH="/Library/TeX/texbin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export EDITOR=nvim
export CLICOLOR=1

# Zsh Plugins
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#FFE6F2, bold'
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# export
export PATH="$HOME/.cargo/bin:$PATH"
export EDITOR="nvim"
export VISUAL="nvim"

# sdk
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# SSH
eval "$(ssh-agent -s)"
alias HL='ssh-add ~/.ssh/id_rsa'

# Custom Commands and Aliases
alias c='clear'
alias h='hisyory'
alias q='exit'
alias r='reset'
alias pac='sudo pacman'

# Dir
alias cdd='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias Git='cd /mnt/Dev/Git/'
alias doc='cd ~/Documents/'
alias dow='cd ~/Downloads/'
alias des='cd ~/Desktop/'

# 修改后的 eza 别名，添加排序选项
alias ls='eza --icons --group-directories-first --sort=extension'
alias la='eza -a --icons --group-directories-first --sort=extension'
alias ll='eza -al --icons --group-directories-first --sort=extension'
alias lt='eza -a --tree --level=1 --icons --group-directories-first --sort=extension'
alias music='cmus'
alias p='python'
alias libtoolize='glibtoolize'
alias poweroff='sudo shutdown -h now'
alias v='$EDITOR'
alias nano='$EDITOR'
alias n='$EDITOR'
alias vim='$EDITOR'

# Auto `ls` after `cd`
cd() {
    builtin cd "$@" && ls
}

# PDF Conversion from Markdown
mdpdf() {
    input_file="$1"
    output_file="${input_file%.*}.pdf"
    pandoc "$input_file" -o "$output_file" --pdf-engine=xelatex --toc
}

# Prompt and Command Display Settings
precmd() {
  print
}

# 加载 git-prompt.sh 脚本
source /usr/share/git/completion/git-prompt.sh

# 启用 PROMPT_SUBST 选项，以便在 PROMPT 中自动解析变量
setopt PROMPT_SUBST

# 定义一个变量来存储 Git 分支信息
git_branch=""

# 使用 precmd 函数在每次显示提示符之前更新 Git 分支信息
precmd() {
  if git rev-parse --is-inside-work-tree &>/dev/null; then
    git_branch="%F{208}  $(git branch --show-current)%f"  # 使用橙色显示 Git 分支
  else
    git_branch=""  # 非 Git 仓库则清空分支信息
  fi
}

# 设置 PROMPT，使用 git_branch 变量，并调整颜色
PROMPT='

%F{81}┌───[%F{121}HL%f:%F{121}HL%f] - %F{75}%~%f${git_branch}
%F{81}│
%F{81}│
%F{81}└─%# %f'

# recmd 函数用来更新终端窗口标题
recmd () { print -Pn "\e]2;OWO@WORKING..: %~\a" }

# Zoxide Initialization
eval "$(zoxide init zsh)"

# Custom `yazi` Command Function
function y() {
  tmp="$(mktemp -t "yazi-cwd.XXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

# fcitx5支持
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
