#!/bin/bash

echo "Updating from local"
echo "Updating neovim
 "
cp -rv ~/.config/nvim/ /mnt/Dev/Git/dotfile/

echo "Updating zdhrc"
cp -v ~/.zshrc /mnt/Dev/Git/dotfile/zshrc-Arch

echo "Updating tmux"
cp -rv ~/.config/tmux/ /mnt/Dev/Git/dotfile/

echo "Updating kitty"
cp -rv ~/.config/kitty/ /mnt/Dev/Git/dotfile/

echo "Updating bashrc"
cp -v ~/.bashrc /mnt/Dev/Git/dotfile/bashrc

echo "Updating Note"
cp -rv ~/zettelkasten/ /mnt/Dev/Git/dotfile/
